name: Replace links with uids in copy branch

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        $ThisCommit = "${{ github.sha }}"
        git checkout ⭐Docs
        git reset --hard $ThisCommit
        git merge main
        pip install ./sync-script
        replace_links https://raw.githubusercontent.com/geduardo/quantum-docs-pr/adding-file-script/articles/user-guide/language/uid-map.csv ./Specifications/Language/
        git add .
        git commit -m "Automatic switch of links to xrefs" -a
        git push origin ⭐Docs --force
      shell: pwsh
      
      
